### ISSUE TITLE
No sidebar links on 'Create' page

### ISSUE THREAD

**Issue by KolbeML** [Cyber4All/neutrino#16]
When you navigate to the 'create' page (the 'Upload' link on the sidebar from the other pages), the sidebar links disappear.

**Comment by gshaw1997** [comment]
The links should be rendering. The view doesn't look like this on your copy? Are there any errors being printed in the developer's console?

![create view](https://user-images.githubusercontent.com/15234476/31731706-deb872b4-b403-11e7-963b-057e268dcaac.PNG)
