### ISSUE TITLE
Handlebars Security Alert

### ISSUE THREAD

**Issue by DonSeannelly** [Cyber4All/neutrino#28]
The repository produced a vulnerability alert:
> We found a potential security vulnerability in one of your dependencies.
> 
> The handlebars dependency defined in package-lock.json has a known moderate severity security vulnerability in version range < 4.0.0 and should be updated.

This should be addressed before merging into onion.

**Comment by KolbeML** [comment]
This was resolved in the merge, repository is ready for deletion
